// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqaS4gJHfdl3wXfJ9RtLF2MAHyGUueE0A',
    appId: '1:244645064126:web:8f60e27e3cbebd5686ddef',
    messagingSenderId: '244645064126',
    projectId: 'green-cdcba',
    authDomain: 'green-cdcba.firebaseapp.com',
    storageBucket: 'green-cdcba.appspot.com',
    measurementId: 'G-NDB5031P8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0073-GBllS2n98tu4j7X9nL-IZn1AMxo',
    appId: '1:244645064126:android:f43b27c540eb50bd86ddef',
    messagingSenderId: '244645064126',
    projectId: 'green-cdcba',
    storageBucket: 'green-cdcba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7Zxw4cKsdZJANwxzGvURWY8PB-qLOBk',
    appId: '1:244645064126:ios:9be85d823007ddb986ddef',
    messagingSenderId: '244645064126',
    projectId: 'green-cdcba',
    storageBucket: 'green-cdcba.appspot.com',
    iosClientId: '244645064126-i1fcbcs1a1ka6r8dpv788d3hr025np5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi7Zxw4cKsdZJANwxzGvURWY8PB-qLOBk',
    appId: '1:244645064126:ios:9be85d823007ddb986ddef',
    messagingSenderId: '244645064126',
    projectId: 'green-cdcba',
    storageBucket: 'green-cdcba.appspot.com',
    iosClientId: '244645064126-i1fcbcs1a1ka6r8dpv788d3hr025np5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourQuest',
  );
}
